### ISSUE TITLE
Error joining multiple domains using Picos_fifos

### ISSUE THREAD

**Issue by koonwen** [ocaml-multicore/picos#234]
Hey! I encountered a weird error when trying to run the `Picos_fifos` scheduler on multiple domains and then waiting for them to complete

```
TID 0
TID 0
Fatal error: exception Invalid_argument("must be called from the main thread on the main domain")
```
The assertions say that we're on the main thread and domain, and it seems to only happen when I run the picos scheduler in the domain. I'm wondering if something could be escaping from the scheduler that's causing this bug.

```ocaml
let () =
  let show_tid () = Printf.printf "TID %d\n" (Thread.id (Thread.self ())) in
  show_tid ();
  let domains =
    List.init 4 (fun _ -> Domain.spawn (fun () -> Picos_fifos.run ignore))
  in
  assert (Domain.is_main_domain ());
  show_tid ();
  List.iter Domain.join domains
```

**Comment by polytypic** [comment]
That error comes from `Picos_select`, which needs to [configured](https://ocaml-multicore.github.io/picos/doc/picos/Picos_select/index.html#val-configure).  Add a call to `Picos_select.configure ()` from the main domain before spawning other domains.

**Comment by koonwen** [comment]
Thanks @polytypic! That fixes it. 

> The potential need to configure Picos_select should be mentioned more clearly in the documentation of Picos_fifos.

I agree, probably something like this will be useful:

"This scheduler internally uses `Unix.select`. If running multiple domains that each run this scheduler, `Picos_select.configure` must be called by the main domain **before** spawning other domains. Alternatively, spawn new domains within the main domains scheduler which automatically calls configure"

I see this is also the case with `Picos_threaded` scheduler, so it would be good to add it there too. I can help to add this if you like
