### ISSUE TITLE
Consider splitting Picos into (at least) two packages

### ISSUE THREAD

**Issue by polytypic** [ocaml-multicore/picos#87]
For example, 
- a core `picos` package would include `picos` and maybe `picos.sync` and more strongly maybe `picos.stdio`.
- an additional `picos_samples` package would contain other things (e.g. sample schedulers) not strictly needed by the core package.

**Comment by polytypic** [comment]
Thinking about this later, I started thinking about packaging things the opposite/different way:
* a `picos_core` package with just the core Picos framework (i.e. which is currently `picos`)
* a `picos` package that includes both the core and everything else in this repository.

**Comment by zoj613** [comment]
I'm getting a `library picos_mux not found` error when including `picos_mux` in libraries list inside a dune file. picos_mux has been installed and picos_io gets included just fine. Is there something i'm missing here?

**Comment by polytypic** [comment]
The `picos_mux` package contains multiple libraries `picos_mux.fifo`, `picos_mux.multififo`, and `picos_mux.random`.
